// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exceltosql.Models;

public partial class his_icd_diagnosis
{
    public int IcdID { get; set; }

    public string IcdCode { get; set; }

    public string LD { get; set; }
}