// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using exceltosql.Models;

namespace exceltosql.Models;

public partial class Medisuite_rel2Context : DbContext
{
    public Medisuite_rel2Context(DbContextOptions<Medisuite_rel2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<his_icd_diagnosis> his_icd_diagnoses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<his_icd_diagnosis>(entity =>
        {
            entity.HasKey(e => e.IcdID);

            entity.ToTable("his_icd_diagnosis");

            entity.Property(e => e.IcdCode)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.LD).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    public DbSet<exceltosql.Models.emp> emp { get; set; } = default!;
}